name = "SharedMemSparseLU"
uuid = "c3e7fdff-16c4-49b2-90b5-77b469c69de3"
authors = ["John Omotani <john.omotani@ukaea.uk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"

[compat]
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
SparseMatricesCSR = "0.6.7"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
